### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by badboybackagain** [kingster/FullonSMS-API#1]
I copied the files on my WAMP Server...running on my local machine. When I tried to call sendsms.php from browser, I am getting error as "access error : couldn't connect to host" What am I doing wrong? I have installed curl too and have restarted the server also...please help..

**Comment by kingster** [comment]
Make sure you are connected directly to internet. If you are connected via proxy server you need to change accordingly.  Also try to open the url in the browser itself to see if the website is opening for you or not.

**Comment by badboybackagain** [comment]
Hey kingster, Thanks for replying. I checked and found, proxy was the culprit. THanks a lot for guiding me on this.

Regards,
Abhishek
